# -*- Mode: Python; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-
### BEGIN LICENSE
# Copyright (C) 2012-2013 qnub <qnub.ru@gmail.com>
# This file is distributed under the license LGPL version 3 or later
### END LICENSE

### DO NOT EDIT THIS FILE ###

'''facade - makes omweather_lib package easy to refactor

while keeping its api constant'''
from . helpers import set_up_logging
from . omweatherconfig import get_version

